server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.woniuxy.pojo
  
spring:
  application:
    name: SPRINGCLOUD-PROVIDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password:
    dbcp2: 
      min-idle: 5   #连接池最小连接数
      initial-size: 5   #初始化大小
      max-total: 10     #最大
      max-wait-millis: 200 
           #最大等待时间
eureka:
  client:
    service-url: 
      defaultZone: http://eurekaserver9001.com:9001/eureka/
#                   http://eurekaserver9002.com:9002/eureka/,
#                   http://eurekaserver9003.com:9003/eureka/
  instance:
    instance-id: woniu58-provider-8002    #配置中心显示微服务的名称
    ip-address: true  #是否显示微服务的url
info:
  app.name: SpringCloud58
  auther: wang
  message: this project is get product info
      